<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.nc</groupId>
  <artifactId>form-engine</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>Form Engine</name>
  <description>An app to save dinamically formatted formularies</description>
  <packaging>pom</packaging>
   <properties>
        <java.version>21</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-boot.version>3.2.2</spring-boot.version>
        <form-engine.version>0.0.1-SNAPSHOT</form-engine.version>
    </properties>
  <modules>
  	<module>form-engine-definition-model</module>
  	<module>form-engine-definition-business</module>
  	<module>form-engine-definition-businessimpl</module>
  	<module>form-engine-definition-data</module>
  	<module>form-engine-definition-dataimpl</module>
  	<module>form-engine-submission-model</module>
  	<module>form-engine-submission-data</module>
  	<module>form-engine-submission-dataimpl</module>
  	<module>form-engine-submission-business</module>
  	<module>form-engine-submission-businessimpl</module>
  	<module>form-engine-rest</module>
  </modules>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.nc</groupId>
                <artifactId>form-engine-definition-model</artifactId>
                <version>${form-engine.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nc</groupId>
                <artifactId>form-engine-definition-data</artifactId>
                <version>${form-engine.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nc</groupId>
                <artifactId>form-engine-definition-dataimpl</artifactId>
                <version>${form-engine.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nc</groupId>
                <artifactId>form-engine-definition-business</artifactId>
                <version>${form-engine.version}</version>
            </dependency>
            <dependency>
            	<groupId>com.nc</groupId>
            	<artifactId>form-engine-definition-businessimpl</artifactId>
            	<version>${form-engine.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nc</groupId>
                <artifactId>form-engine-submission-model</artifactId>
                <version>${form-engine.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nc</groupId>
                <artifactId>form-engine-submission-data</artifactId>
                <version>${form-engine.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nc</groupId>
                <artifactId>form-engine-submission-dataimpl</artifactId>
                <version>${form-engine.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nc</groupId>
                <artifactId>form-engine-submission-business</artifactId>
                <version>${form-engine.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nc</groupId>
                <artifactId>form-engine-submission-businessimpl</artifactId>
                <version>${form-engine.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nc</groupId>
                <artifactId>form-engine-submission-rest</artifactId>
                <version>${form-engine.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
     <dependency>
		<groupId>org.projectlombok</groupId>
		<artifactId>lombok</artifactId>
		<optional>true</optional>
	</dependency>
    </dependencies>
  	<build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.11.0</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                        <parameters>true</parameters>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>